name: build and Publish image to docker hub
on:
  [workflow_dispatch]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v
      - name: build image
        run: docker build ./DockerToECS/ -t iamhardeep22/devops-credit:latest
      - name: push image
        run: docker login -u iamhardeep22 -p ${{ secrets.DOCKER_HUB_TOKEN }} 
          docker push iamhardeep22/devops-credit:latest
